@Restaurants.API_HostAddress = http://localhost:5140

###
GET {{Restaurants.API_HostAddress}}/api/restaurants

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
"Name": "Spicy Deligts",
"Description": "A culinary experience like no other",
"Category": "Fine Dining",
"HasDelivery": true,
"ContactEmail":"info@restaurant1.com",
"ContactNumber": "555-123-4567",
"City": "Dera Ismail Khan",
"Street": "Street-1",
"PostalCode": "52321"
}